[package]
name = "mdscrape"
version = "0.1.1"
authors = ["Sahan Fernando <sahan.h.fernando@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10", features = ["json", "stream"] }
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }
serde = { version = "1.0", features = ["derive"] }
walkdir = "2.3.1"
indicatif = "0.15.0"
argparse = "*"
futures = "0.3.5"
url = "*"
tokio-retry = "0.2"
rand = "*"
